In [ ]:
!pip install gym 

In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env=gym.make("FrozenLake-v0")

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.10
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = []

for episode in range(num_episodes):
  state = env.reset()

  done = False
  rewards_current_episode = 0
  for step in range(max_steps_per_episode):
    exporation_rate_threshold = random.uniform(0, 1)
    if exporation_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)

    q_table[state, action] = q_table[state, action]*(1-learning_rate) + learning_rate*(reward + discount_rate * np.max(q_table[new_state, :]))

    state = new_state
    rewards_current_episode += reward

    if done == True:
      break
  exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
  rewards_all_episodes.append(rewards_current_episode)


rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("--------Average reward per thousand episodes---------------\n")

for r in rewards_per_thousand_episodes:
  print(count, ": ", str(sum(r/1000)))
  count += 1000

print("\n\n ******Q-Table******\n")
print(q_table)





--------Average reward per thousand episodes---------------

1000 :  0.02900000000000002
2000 :  0.21500000000000016
3000 :  0.4250000000000003
4000 :  0.5620000000000004
5000 :  0.6580000000000005
6000 :  0.6740000000000005
7000 :  0.6780000000000005
8000 :  0.6760000000000005
9000 :  0.6630000000000005
10000 :  0.6760000000000005


 ******Q-Table******

[[0.56110326 0.51357322 0.5167374  0.50939989]
 [0.41572739 0.39308457 0.35484561 0.50441119]
 [0.4279542  0.41169983 0.40483166 0.46794146]
 [0.30497864 0.28435433 0.18142042 0.45354365]
 [0.58666248 0.40038435 0.41645167 0.33258357]
 [0.         0.         0.         0.        ]
 [0.20348465 0.15153949 0.36380643 0.11751145]
 [0.         0.         0.         0.        ]
 [0.45261654 0.50133322 0.41706646 0.64340549]
 [0.28617986 0.73102146 0.56138651 0.34788167]
 [0.64290892 0.5074559  0.33589001 0.28658481]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41199809 0.31596925 0.83287

In [ ]:
for episode in range(10):
  state = env.reset()
  done = False
  print("----EPISODE  ", episode+1, "-------\n\n\n\n")
  time.sleep(1)
  for step in range(max_steps_per_episode):
    clear_output(wait = True)
    env.render()
    time.sleep(0.2)

    action = np.argmax(q_table[state,:])
    new_state, reward, done, info = env.step(action)

    if done:
      clear_output(wait = True)
      env.render()
      if reward == 1:
        print("*****You reached the goal!*****")
        time.sleep(2)
      else:
        print("*****You fell through a hole!******")
        time.sleep(2)
      clear_output(wait = True)
      break

    state = new_state

env.close()



  (Left)
SFFF
FHFH
FFFH
HFFG
*****You fell through a hole!******
